tx_90:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin,  kdl_kinematics_plugin/KDLKinematicsPlugin
  opw_kinematics_geometric_parameters:
    a1: 0.05
    a2: 0.0
    b:  0.05
    c1: 0.478
    c2: 0.425
    c3: 0.425 
    c4: 0.1
  opw_kinematics_joint_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  opw_kinematics_joint_sign_corrections: [1, 1, 1, 1, 1, 1]
